################################################################################
# 03_figures.R
#
# Code to reproduce all main and supplementary figures.
#
# Assumes the following pre-computed result files exist (generated by
# 01_main_analysis.R and 02_recurrent_aneuploidies.R):
#
#   - metadata      : sample-level metadata with Malignant_Mean_AS, Cancer_type,
#                     high_vs_low_comp, num_cells_total, etc.
#   - malig_data    : per-sample malignant-cell AS summary
#   - cells_AS_df   : gene-level AS per malignant cell (genes × samples)
#   - samples_as_descriptive_summary : per-sample AS group cell counts
#   - samples_CNheterogeneity_pairwaiseCor_df : AHS per sample
#   - ssgsea meta-analysis CSVs
#   - pseudo-bulk lmFit enrichment CSVs
#   - TCGA GSEA/enrichment result CSVs
#   - Louvain subclone summary CSV
#
# Paths for these files should be updated to your local copies.
################################################################################

suppressMessages({
  library(tidyverse); library(dplyr); library(tidyr); library(reshape2)
  library(ggplot2); library(ggrepel); library(ggpubr)
  library(patchwork); library(cowplot); library(ggnewscale)
  library(geomtextpath); library(Cairo); library(ragg)
})

# ---- shared theme & colours (same as 01_main_analysis.R) ----
graph_theme <- theme_minimal() +
  theme(
    axis.text        = element_text(size = 17),
    axis.title       = element_text(size = 22),
    plot.title       = element_text(hjust = 0.5, face = "bold", size = 24),
    axis.text.x      = element_text(angle = 0, size = 17),
    axis.text.y      = element_text(size = 17),
    legend.key.size  = unit(1, "cm"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.title     = element_text(size = 17),
    legend.text      = element_text(size = 15),
    panel.border     = element_blank(),
    axis.line        = element_line(color = "black"),
    strip.text       = element_text(size = 18)
  )

highASColor <- "#004D40"
midASColor  <- "#26A69A"
lowASColor  <- "#B2DFDB"


# ==============================================================================
# Dataset Overview (Donut / Pie Chart)
# ==============================================================================
# Input: files_map — data.frame with columns Cancer_type, Study, Sample
#   (one row per sample)
#
# The inner ring shows cancer types; the outer ring shows studies.

plot_dataset_overview <- function(files_map) {
  # Helper: generate progressively lighter shades per sub-group
  subcolors <- function(.dta, main, mainCol) {
    tmp    <- cbind(.dta, 1, "col")
    colnames(tmp)[4:5] <- c("n", "col")
    for (g in unique(.dta[[main]])) tmp$col[.dta[[main]] == g] <- mainCol[g]
    u      <- unlist(by(tmp$n, tmp[[main]], cumsum))
    n      <- nrow(.dta)
    subcol <- character(n)
    for (i in seq_len(n)) {
      t1      <- col2rgb(tmp$col[i]) / 256
      subcol[i] <- rgb(t1[1], t1[2], t1[3], 1 / (1 + u[i]))
    }
    subcol
  }

  counts   <- files_map %>%
    group_by(Cancer_type, Study) %>%
    dplyr::summarise(count = n(), .groups = "drop")
  mainCol  <- setNames(
    c("dodgerblue4","deeppink3","forestgreen","orange","red3","yellow",
      "bisque3","purple","lightblue","lightpink","lightgreen","darkcyan",
      "darkred","darkorange","chocolate4")[seq_along(unique(counts$Cancer_type))],
    unique(counts$Cancer_type)
  )
  subcol   <- setNames(subcolors(counts, "Cancer_type", mainCol), counts$Study)

  ggplot(counts) +
    geom_rect(aes(ymin = cumsum(count) - count, ymax = cumsum(count),
                  xmin = 0, xmax = 1, fill = Cancer_type), alpha = 0.7) +
    geom_text(
      data = counts %>%
        group_by(Cancer_type) %>%
        dplyr::summarise(count = sum(count), .groups = "drop"),
      aes(x = 1.05, y = cumsum(count) - count / 2,
          label = paste0(Cancer_type, " (", count, ")")), size = 7
    ) +
    scale_fill_manual(values = mainCol) + guides(fill = "none") +
    new_scale_fill() +
    geom_rect(aes(ymin = cumsum(count) - count, ymax = cumsum(count),
                  xmin = 1.1, xmax = 1.3, fill = Study)) +
    scale_fill_manual(values = subcol) +
    theme_void() + coord_polar(theta = "y") +
    theme(legend.position = "none")
}


# ==============================================================================
# Per-Sample Aneuploidy Score Distribution
# ==============================================================================
# Shows boxplots of per-cell AS for each sample (sorted by mean AS),
# with a line tracing the sample-level mean.
#
# Inputs:
#   cells_AS_df      — data.frame (cells × samples) of per-cell AS values
#   metadata_ordered — metadata sorted by Malignant_Mean_AS

plot_AS_distribution <- function(cells_AS_df, metadata_ordered) {
  common <- intersect(rownames(metadata_ordered), colnames(cells_AS_df))
  cells_AS_sort <- cells_AS_df[,
    common[order(match(common, rownames(metadata_ordered)))], drop = FALSE]

  long <- melt(cells_AS_sort, id.vars = NULL,
               variable.name = "Column", value.name = "Value") %>%
    drop_na()

  ggplot() +
    geom_boxplot(
      data    = long,
      aes(x = Column, y = Value),
      fill    = "lightblue", color = alpha("gray", 0.5),
      outlier.color = "lightgray", outlier.size = 0.5, alpha = 0.6
    ) +
    geom_line(
      data    = metadata_ordered,
      aes(x = name, y = Malignant_Mean_AS, group = 1),
      color   = "#333333", linewidth = 1
    ) +
    scale_x_discrete(expand = expansion(mult = c(0.02, 0.02))) +
    labs(x = "Sample (sorted by increasing mean AS)",
         y = "Aneuploidy Score") +
    graph_theme +
    theme(axis.text.x = element_blank()) +
    scale_y_continuous(
      breaks = seq(round(min(metadata_ordered$Malignant_Mean_AS)),
                   round(max(metadata_ordered$Malignant_Mean_AS) + 4),
                   by = 2)
    )
}


# ==============================================================================
# Cell AS Histogram
# ==============================================================================
# Histogram of per-cell AS values across all malignant cells.
#
# Input: long data.frame with column 'Value' (per-cell AS)

plot_cell_AS_histogram <- function(cells_long) {
  ggplot(cells_long, aes(x = Value)) +
    geom_histogram(color = "darkgray", fill = "gray", binwidth = 1) +
    labs(x = "Aneuploidy Score",
         y = "Number of Cells") +
    graph_theme +
    scale_x_continuous(
      breaks = round(seq(min(cells_long$Value), max(cells_long$Value), by = 2), 1)
    )
}


# ==============================================================================
# AS Group Proportions per Sample
# ==============================================================================
# Stacked bar chart showing the fraction of High / Mid / Low AS cells per
# sample, sorted by increasing sample-level mean AS.
#
# Input: samples_as_descriptive_summary — data.frame with columns
#   highAS_cells, midAS_cells, lowAS_cells, Malignant_Mean_AS, Sample

plot_AS_groups_stacked <- function(d) {
  d$Sample <- reorder(d$Sample, d$Malignant_Mean_AS)

  df_long <- d %>%
    pivot_longer(cols = c(highAS_cells, lowAS_cells, midAS_cells),
                 names_to = "Cell_Type", values_to = "Count") %>%
    mutate(Cell_Type = factor(Cell_Type,
                              levels = c("highAS_cells", "midAS_cells", "lowAS_cells")))

  ggplot(df_long, aes(x = Sample, y = Count, fill = Cell_Type)) +
    geom_bar(position = "fill", stat = "identity", width = 1) +
    scale_y_continuous(labels = scales::percent_format(), expand = c(0, 0)) +
    labs(x = "Samples (sorted by increasing AS)",
         y = "% of Cells",
         fill = "Cell Groups") +
    scale_fill_manual(
      values = c(lowAS_cells  = lowASColor,
                 midAS_cells  = midASColor,
                 highAS_cells = highASColor),
      breaks = c("highAS_cells", "midAS_cells", "lowAS_cells"),
      labels = c("High AS", "Mid AS", "Low AS")
    ) +
    graph_theme +
    theme(axis.text.x        = element_blank(),
          panel.grid.major.x = element_blank())
}


# ==============================================================================
# ssGSEA Meta-Analysis Dot Plot
# ==============================================================================
# Dot plot of pooled effect sizes from the ssGSEA meta-analysis.
# Colour: red = positive (up in high-AS), blue = negative.
# Transparency encodes q-value (more opaque = more significant).
#
# Input:
#   summary_results — output of ssgsea_metaAnalysis()
#   (Pathway, PooledEffectSize, Qvalues)

plot_ssgsea_dotplot <- function(summary_results) {
  df <- summary_results %>%
    drop_na() %>%
    arrange(PooledEffectSize) %>%
    mutate(
      name        = gsub("HALLMARK_", "", Pathway),
      name        = factor(name, levels = name),
      color       = ifelse(PooledEffectSize > 0, "#ae282c", "#2066a8"),
      alpha_value = scales::rescale(Qvalues, to = c(0.05, 1))
    )

  ggplot(df, aes(x = PooledEffectSize, y = name,
                 color = color, alpha = alpha_value)) +
    geom_point(size = 2.5) +
    scale_color_identity() +
    scale_alpha_continuous(range = c(0.05, 1), trans = "reverse",
                           name = "q-value") +
    labs(x = "ssGSEA Pooled Effect Size\n(High AS vs Low AS)",
         y = "HALLMARK Pathways") +
    graph_theme +
    theme(axis.text.y = element_text(size = 13),
          legend.title = element_text(size = 20)) +
    guides(alpha = guide_legend(override.aes = list(size = 6)))
}


# ==============================================================================
# Pathway Heatmap
# ==============================================================================
# Two-column heatmap comparing enrichment for HALLMARK pathways.  
# This example displays data for pseudo-bulk and TCGA datasets and the colour scale encodes log10(1/qvalue) × direction.
# Similar logic is used for all enrichment comparisons throughout the paper.
#
# Inputs:
#   merged_df_long — long-format data.frame with columns:
#     ID, name (pathway label), Method ("TCGA" or "Pseudo"),
#     value (enrichment score), qval
#   q_val_thres — significance threshold for black tile border (default 0.05)
#   plot_limit  — colour scale limit (default 25)

plot_make_enrichment_heatmap <- function(merged_df_long, q_val_thres = 0.05,
                                    plot_limit = 25, highlight_ids = NULL) {
  if (!is.null(highlight_ids)) {
    merged_df_long <- merged_df_long[merged_df_long$ID %in% highlight_ids, ]
  }

  # Order by TCGA value (decreasing)
  tcga_order <- merged_df_long %>%
    filter(Method == "TCGA") %>%
    arrange(desc(value))
  tcga_order$name <- factor(tcga_order$name, levels = tcga_order$name)

  merged_df_long <- merged_df_long %>%
    mutate(
      name   = factor(name, levels = levels(tcga_order$name)),
      Method = factor(Method, levels = c("TCGA", "Pseudo"))
    )

  make_tile_plot <- function(df_sub, x_lab, y_lab = NULL, lim = plot_limit) {
    p <- ggplot(df_sub, aes(x = Method, y = name, fill = value)) +
      geom_tile(color = "white") +
      scale_fill_gradientn(
        colours = c("#2066a8", "gray90", "#ae282c"),
        values  = scales::rescale(c(-lim, 0, lim)),
        limits  = c(-lim, lim), oob = scales::squish,
        name    = "log10\n(1/qvalue)\n& direction"
      ) +
      geom_tile(data = df_sub[df_sub$qval < q_val_thres, ],
                color = "black", size = 0.3) +
      labs(x = x_lab, y = if (is.null(y_lab)) "HALLMARK Pathways" else y_lab) +
      graph_theme +
      theme(
        axis.text.x    = element_blank(), axis.ticks.x = element_blank(),
        axis.title.x   = element_text(size = 17),
        axis.text.y    = element_text(size = 10),
        axis.line.x    = element_blank(), axis.line.y = element_blank(),
        legend.key.height = unit(0.8, "cm"), legend.key.width = unit(0.6, "cm"),
        legend.title   = element_text(size = 15),
        legend.text    = element_text(size = 13)
      )
    p
  }

  p_labels <- ggplot(tcga_order, aes(x = Method, y = name)) +
    labs(y = "HALLMARK Pathways", x = "") + geom_blank() + graph_theme +
    theme(axis.text.y = element_text(size = 11),
          axis.text.x = element_blank(), axis.ticks = element_blank(),
          panel.grid = element_blank(), axis.line = element_blank())

  tcga_tile   <- make_tile_plot(merged_df_long[merged_df_long$Method == "TCGA", ],
                                "TCGA") +
    theme(axis.text.y = element_blank(), axis.title.y = element_blank(),
          legend.position = "none")
  pseudo_tile <- make_tile_plot(merged_df_long[merged_df_long$Method != "TCGA", ],
                                "Pseudo-Bulk") +
    theme(axis.text.y = element_blank(), axis.title.y = element_blank(),
          legend.position = "none")
  legend      <- ggpubr::get_legend(
    make_tile_plot(merged_df_long[merged_df_long$Method == "TCGA", ], ""),
    position = "right"
  )

  combined <- plot_grid(p_labels, tcga_tile, pseudo_tile,
                        nrow = 1, align = "h", axis = "tb",
                        rel_widths = c(2, 1, 1))
  plot_grid(combined, legend, rel_widths = c(8, 1))
}

# ==============================================================================
# Enrichment Scatter Plot
# ==============================================================================
# Spearman correlation of enrichment results.
# This example displays data for pseudo-bulk and TCGA datasets.
# Similar logic is used for all enrichment comparisons throughout the paper.
#
# Input: merged_df — data.frame with Pseudo enrichment score, TCGA enrichment score, ID

plot_enrichment_correlation <- function(merged_df) {
  ct   <- cor.test(merged_df$Pseudo, 
                   merged_df$TCGA, 
                   method = "spearman", exact = FALSE)
  rho  <- round(ct$estimate, 4)
  pval <- round(ct$p.value, 4)
  
  lab  <- paste0("rho = ", round(rho, 2), "\np ", 
                 ifelse(pval < 2.2e-16, "< 2.2e-16", 
                        paste0("= ", format.pval(pval, digits = 2))))
  
  ggplot(merged_df, aes(x = Pseudo, y = TCGA)) +
    geom_point() +
    geom_smooth(method = "lm", col = alpha("blue", 0.5), level = 0.95) +
    annotate("text", 
             x = max(merged_df$Pseudo, na.rm = TRUE), 
             y = max(merged_df$TCGA, na.rm = TRUE), 
             label = lab, 
             hjust = 1, vjust = 1, size = 7) +
    geom_text_repel(aes(label = ID), size = 4.5, 
                    box.padding = unit(0.4, "lines"),
                    point.padding = unit(0.5, "lines"),
                    min.segment.length = 0.5) +
    labs(x = "Pseudo-Bulk Enrichment\n(log10(1/qvalue) & direction)",
         y = "TCGA Enrichment\n(log10(1/qvalue) & direction)") + 
    graph_theme
}

# ==============================================================================
# Karyotypic Heterogeneity vs. AS Scatter Plot
# ==============================================================================
# Spearman correlation of AHS (y) vs. sample-level mean AS (x).
#
# Input: metadata_filtered — data.frame with Malignant_Mean_AS, AHS,
#                            AS_Group_maligAS

plot_AHS_vs_AS <- function(metadata_filtered) {
  ct   <- cor.test(metadata_filtered$Malignant_Mean_AS,
                   metadata_filtered$AHS,
                   method = "spearman", exact = FALSE)
  rho  <- round(ct$estimate, 4)
  pval <- round(ct$p.value, 4)
  lab  <- paste0("rho = ", round(rho, 2), "\np ",
                 ifelse(pval < 2.2e-16, "< 2.2e-16",
                        paste0("= ", format.pval(pval, digits = 2))))

  ggplot(metadata_filtered,
         aes(x = Malignant_Mean_AS, y = AHS, color = AS_Group_maligAS)) +
    geom_point() +
    scale_color_manual(
      values = c(lowAS = lowASColor, midAS = midASColor, highAS = highASColor),
      breaks = c("highAS", "midAS", "lowAS"),
      labels = c("High AS", "Mid AS", "Low AS")
    ) +
    geom_smooth(method = "lm", col = alpha("blue", 0.5), level = 0.95) +
    annotate("text",
             x = max(metadata_filtered$Malignant_Mean_AS, na.rm = TRUE),
             y = 0.95, label = lab,
             hjust = 1, vjust = 1, size = 7) +
    labs(x = "Sample Aneuploidy Score",
         y = "Karyotypic Heterogeneity Score",
         color = "Sample AS") +
    graph_theme
}

# ==============================================================================
# Louvain Subclones vs. Sample AS Violin Plot
# ==============================================================================
# Compares Sample AS (Malignant_Mean_AS) across binned groups of Louvain subclones.
# Includes Wilcoxon rank-sum tests between groups.
#
# Input: subclones_metadata_filtered — data.frame with Louvain.clones, 
#                                      Malignant_Mean_AS

plot_subclones_vs_AS <- function(subclones_metadata_filtered) {
  # Group the subclones into categorical bins
  subclones_metadata_filtered$clones <- ifelse(
    subclones_metadata_filtered$Louvain.clones >= 2 & subclones_metadata_filtered$Louvain.clones <= 3, "2-3", 
    ifelse(subclones_metadata_filtered$Louvain.clones >= 4, ">=4", "1")
  )
  subclones_metadata_filtered$clones <- factor(subclones_metadata_filtered$clones, 
                                               levels = c("1", "2-3", ">=4"))
  
  ggplot(subclones_metadata_filtered, aes(x = clones, y = Malignant_Mean_AS)) +
    geom_violin(trim = FALSE, alpha = 0.6, fill = "gray") +
    geom_boxplot(width = 0.1, fill = "white") +
    geom_jitter(alpha = 0.4, size = 1, width = 0.15, height = 0) +
    stat_compare_means(
      method = "wilcox.test",
      comparisons = list(
        c("1", "2-3"), 
        c("2-3", ">=4"), 
        c("1", ">=4")
      ),
      label = "p.format",
      method.args = list(alternative = "two.sided"),
      size = 5
    ) +
    labs(x = "# of Louvain subclones",
         y = "Sample AS") + 
    graph_theme
}

# ==============================================================================
# Within-Subclone Heterogeneity by AS Group
# ==============================================================================
# Violin plot comparing within-subclone karyotypic heterogeneity (AHS = 1 −
# mean pairwise CNA correlation within a Louvain subclone) stratified by the
# sample's AS group.
#
# Input: samples_hete_clusters_data_filtered — data.frame with
#   AHS (per subclone), AS_group

plot_subclone_AHS <- function(samples_hete_clusters_data_filtered) {
  df <- samples_hete_clusters_data_filtered %>%
    mutate(AS_group = factor(AS_group, levels = c("lowAS", "midAS", "highAS")))

  ggplot(df, aes(x = AS_group, y = AHS, fill = AS_group)) +
    geom_violin(trim = FALSE, alpha = 0.6) +
    geom_boxplot(width = 0.1, color = "black", outlier.shape = NA) +
    scale_fill_manual(
      values = c(lowAS = lowASColor, midAS = midASColor, highAS = highASColor),
      labels = c("Low AS", "Mid AS", "High AS")
    ) +
    scale_x_discrete(labels = c(lowAS = "Low AS", midAS = "Mid AS",
                                  highAS = "High AS")) +
    stat_compare_means(
      method = "wilcox.test",
      comparisons = list(c("lowAS", "midAS"), c("midAS", "highAS"),
                         c("lowAS", "highAS")),
      label = "p.format", size = 5
    ) +
    labs(x = "Sample Aneuploidy Score",
         y = "Within-Subclone\nKaryotypic Heterogeneity Score",
         fill = "Sample AS") +
    graph_theme
}


# ==============================================================================
# ssGSEA Effect Size vs. Karyotypic Heterogeneity
# ==============================================================================
# Scatter plot of a single pathway's ssGSEA effect size (y) vs. sample-level
# AHS (x).  Used to show that P53 pathway activation correlates with AHS.
#
# Input:
#   results_sssgsea — data.frame, rows = samples, columns = HALLMARK pathways
#                     (ssGSEA effect sizes), plus columns AHS, Malignant_Mean_AS
#   score           — pathway column name, e.g. "HALLMARK_P53_PATHWAY"

plot_ssgsea_vs_AHS <- function(results_sssgsea, score) {
  ct   <- cor.test(results_sssgsea$AHS, results_sssgsea[[score]],
                   method = "spearman", exact = FALSE)
  rho  <- round(ct$estimate, 4)
  pval <- round(ct$p.value, 4)
  lab  <- paste0("rho = ", round(rho, 2), "\np ",
                 ifelse(pval < 2.2e-16, "< 2.2e-16",
                        paste0("= ", format.pval(pval, digits = 2))))

  ggplot(results_sssgsea, aes(x = AHS, y = .data[[score]],
                               color = .data[[score]])) +
    geom_point() +
    geom_smooth(method = "lm", col = alpha("blue", 0.5), level = 0.95) +
    scale_color_gradient2(midpoint = 0, low = "#2066a8",
                          high = "#ae282c", mid = "gray90") +
    annotate("text",
             x = max(results_sssgsea$AHS, na.rm = TRUE),
             y = 0.95, label = lab,
             hjust = 1, vjust = 1, size = 7) +
    labs(x = "Karyotypic Heterogeneity Score",
         y = paste0(gsub("HALLMARK_", "", score), "\nssGSEA Effect Size"),
         color = "ssGSEA\nEffect Size") +
    graph_theme
}

# ==============================================================================
# Cancer-Type Specific Meta-Analysis Heatmap
# ==============================================================================
# Heatmap displaying pooled effect sizes across individual cancer lineages.
#
# Input: sc_per_cancer_df — output of ssgsea_metaAnalysis_perCancer()
#        pathway_order    — optional character vector dictating the Y-axis order

plot_cancer_type_meta_analysis_heatmap <- function(sc_per_cancer_df, pathway_order = NULL, 
                                                   q_val_thres = 0.05, plot_limit = 0.2) {
  
  sc_per_cancer_df$name <- gsub("HALLMARK_", "", sc_per_cancer_df$Pathway)
  
  if (is.null(pathway_order)) {
    pathway_order <- sc_per_cancer_df %>%
      group_by(name) %>%
      summarize(median_effect = median(PooledEffectSize, na.rm = TRUE)) %>%
      arrange(median_effect) %>%
      pull(name)
  }
  
  sc_per_cancer_df <- sc_per_cancer_df %>%
    filter(name %in% pathway_order) %>%
    mutate(name = factor(name, levels = pathway_order))
  
  ggplot(sc_per_cancer_df, aes(x = Cancer_type, y = name, fill = PooledEffectSize)) +
    geom_tile(color = "white") +
    scale_fill_gradientn(
      colours = c("#2066a8", "gray90", "#ae282c"),
      values  = scales::rescale(c(-plot_limit, 0, plot_limit)),
      limits  = c(-plot_limit, plot_limit), 
      oob     = scales::squish, 
      name    = "Pooled\nEffect Size"
    ) +
    geom_tile(
      data = subset(sc_per_cancer_df, Qvalues < q_val_thres), 
      color = "black", size = 0.5
    ) +
    labs(x = "Cancer Type", y = "HALLMARK Pathways") +
    graph_theme +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
      axis.text.y = element_text(size = 14),
      axis.line   = element_blank(),
      panel.grid  = element_blank(),
      axis.ticks  = element_blank(),
      legend.key.height = unit(0.8, "cm"),
      legend.key.width  = unit(0.6, "cm")
    )
}

# ==============================================================================
#### Supplementary Figures
# ==============================================================================

# ==============================================================================
# Cell Type Distribution per Sample
# ==============================================================================
# Stacked bar chart: malignant vs non-malignant cells per sample.
#
# Input: df — data.frame with columns numMalignant, numNonMalignant, Study, Sample

plot_cell_distribution <- function(df) {
  df$name <- reorder(paste0(df$Study, "/", df$Sample), df$numMalignant)
  df_long <- df %>%
    pivot_longer(cols = c(numMalignant, numNonMalignant),
                 names_to = "type", values_to = "Count")

  ggplot(df_long, aes(x = name, y = Count, fill = type)) +
    geom_bar(position = "stack", stat = "identity") +
    labs(x = "Sample (sorted by cell count)",
         y = "# Cells",
         fill = "Cell Type") +
    scale_fill_manual(values = c("#ff6666", "#cccccc"),
                      labels = c("Malignant", "Non-malignant")) +
    graph_theme +
    theme(axis.text.x = element_blank())
}


# ==============================================================================
# Number of Expressed Genes per Sample
# ==============================================================================
# Histogram of the number of expressed genes per sample after quality filtering.
#
# Input: df — data.frame with column numGenes

plot_expressed_genes <- function(df) {
  ggplot(df, aes(numGenes)) +
    geom_histogram(color = "darkgray", fill = "lightgray") +
    xlab("# Expressed Genes (per Sample)") +
    ylab("# Samples") +
    stat_bin(aes(label = ifelse(..count.. > 0, as.character(..count..), "")),
             geom = "text", vjust = -0.5, size = 4) +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    graph_theme
}

# ==============================================================================
# Sample Distribution by Cancer Type and AS Groups Bar Plot
# ==============================================================================
# Displays the count of samples per cancer type, split into groups based on 
# whether they have sufficient (>=30) High-AS and Low-AS cells.
#
# Input: d — data.frame with Cancer_type, highAS_cells, lowAS_cells

plot_sample_AS_distribution <- function(d) {
  
  # 1. Classify samples into groups based on cell counts
  d$group <- ifelse(d$highAS_cells >= 30 & d$lowAS_cells >= 30, 'High and Low AS groups', 
                    ifelse(d$highAS_cells >= 30 & d$lowAS_cells < 30, 'Not enough Low AS cells', 
                           ifelse(d$highAS_cells < 30 & d$lowAS_cells >= 30, 'Not enough High AS cells', 'Not enough High & Low AS cells')))
  
  # Factorize to ensure specific plotting order
  d$group <- factor(d$group, levels = c("Not enough Low AS cells", 
                                        "Not enough High AS cells", 
                                        "Not enough High & Low AS cells",
                                        "High and Low AS groups"))
  
  # 2. Summarize counts per cancer type and group
  df_cancerType <- d %>%
    group_by(Cancer_type, group) %>%
    dplyr::summarise(count = n(), .groups = "drop")
  
  # 3. Create mapping for x-axis placement
  x_mapping <- d %>%
    distinct(Cancer_type) %>%
    arrange(Cancer_type) %>%
    mutate(x = row_number())
  
  # Classify bar type: 'main' (has both groups) vs 'stack' (missing groups)
  df_cancerType <- df_cancerType %>%
    mutate(bar_type = ifelse(group == "High and Low AS groups", "main", "stack"))
  
  # Count per cancer type how many bar types are present to adjust positioning
  bar_type_count <- df_cancerType %>%
    group_by(Cancer_type) %>%
    summarise(n_bar_types = n_distinct(bar_type), .groups = "drop")
  
  # Merge info and calculate exact x-position (xpos) for dodging/stacking
  df_cancerType <- df_cancerType %>%
    left_join(x_mapping, by = "Cancer_type") %>%
    left_join(bar_type_count, by = "Cancer_type") %>%
    mutate(xpos = case_when(
      n_bar_types == 1 ~ x,               # Only one group → center
      bar_type == "main" ~ x - 0.2,       # Main bar (green) → left
      bar_type == "stack" ~ x + 0.2       # Stacked bars (gray/black) → right
    ))
  
  # 4. Generate the Plot
  ggplot() +
    # Stacked bars for samples lacking sufficient high/low cells
    geom_bar(data = df_cancerType %>% filter(bar_type == "stack"),
             aes(x = xpos, y = count, fill = group),
             stat = "identity", position = "stack", width = 0.4) +
    # Separate bar for samples with sufficient high and low cells
    geom_bar(data = df_cancerType %>% filter(bar_type == "main"),
             aes(x = xpos, y = count, fill = group),
             stat = "identity", width = 0.4) +
    scale_x_continuous(breaks = x_mapping$x,
                       labels = x_mapping$Cancer_type) +
    scale_fill_manual(values = c("lightgray", "darkgray", "black", "darkgreen"),
                      labels = c("<30 Cells in Low-AS",
                                 "<30 Cells in High-AS",
                                 "<30 Cells in both AS groups",
                                 "≥30 Cells in both AS groups")) +
    labs(x = "Cancer Type", 
         y = "# Samples", 
         fill = "High and Low\nAS Groups") +
    graph_theme +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 13))
}

# ==============================================================================
# Mean Expressed Genes per UMI Sample by AS Group
# ==============================================================================
# Displays a violin and boxplot of mean expressed genes across AS groups.
# Includes paired Wilcoxon tests comparing other groups to the highAS group.
#
# Note: To plot Mitochondrial Genes instead, duplicate this function, change 
# the y-axis aesthetic to `y = mean_percent_mito`, and update the y-axis label.
#
# Input: ngenes_long — data.frame with AS_group, mean_ngenes (average number of 
#                      expressed genes per cell), and name (sample ID).

plot_expressed_genes_vs_AS <- function(ngenes_long) {
  
  # Ensure the factor levels are set correctly for the plotting order
  ngenes_long$AS_group <- factor(ngenes_long$AS_group, 
                                 levels = c("Non malignant", "lowAS", "midAS", "highAS"))
  
  ggplot(ngenes_long, aes(x = AS_group, y = mean_ngenes)) +
    geom_violin(fill = "gray90", width = 1, trim = FALSE) +
    geom_boxplot(width = 0.1, fill = "white", outlier.shape = NA) +
    stat_compare_means(
      comparisons = list(
        c("Non malignant", "highAS"),
        c("midAS", "highAS"),
        c("lowAS", "highAS")
      ),
      method = "wilcox.test",
      paired = TRUE,
      label = "p.format", 
      mapping = aes(group = name), 
      size = 5
    ) + 
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_x_discrete(labels = c(
      "Non malignant" = "Non-Malignant",
      "lowAS" = "Low AS",
      "midAS" = "Mid AS",
      "highAS" = "High AS"
    )) +
    labs(
      x = "Aneuploidy Score Group",
      y = "Mean Expressed Genes\nper UMI Sample\n(by Cell Group)"
    ) +
    graph_theme
}

# ==============================================================================
# AHS Distribution: All vs. High/Low AS Samples
# ==============================================================================
# Compares AHS between all samples and the subset with ≥30 cells in both the
# high-AS and low-AS groups.
#
# Input: metadata_filtered — data.frame with columns AHS, high_vs_low_comp

plot_AHS_groups <- function(metadata_filtered) {
  df_all    <- metadata_filtered %>%
    transmute(score = AHS, group = "All Samples")
  df_subset <- metadata_filtered %>%
    filter(high_vs_low_comp) %>%
    transmute(score = AHS, group = "Samples with High and Low")
  plot_df <- bind_rows(df_all, df_subset)

  ggplot(plot_df, aes(x = group, y = score, fill = group)) +
    geom_violin(trim = FALSE, alpha = 0.6) +
    geom_boxplot(width = 0.1, color = "black", outlier.shape = NA) +
    geom_jitter(alpha = 0.4, size = 1, width = 0.15) +
    scale_fill_manual(values = c("All Samples"              = "lightgrey",
                                  "Samples with High and Low" = "darkgrey")) +
    stat_compare_means(
      method = "wilcox.test",
      comparisons = list(c("All Samples", "Samples with High and Low")),
      label = "p.format", size = 4
    ) +
    coord_cartesian(ylim = c(0, 1.2)) +
    labs(y = "Karyotypic Heterogeneity Score") +
    graph_theme +
    theme(legend.position = "none", axis.title.x = element_blank())
}


# ==============================================================================
# Louvain Subclone Count Histogram
# ==============================================================================
# Input: summary — data.frame with column X..Louvain.clones

plot_louvain_histogram <- function(summary) {
  ggplot(summary, aes(x = X..Louvain.clones)) +
    geom_histogram(fill = "darkgreen", binwidth = 1) +
    labs(x = "# CN Subclones per Sample",
         y = "# Samples") +
    graph_theme
}

# ==============================================================================
# Subclone Enrichment Bar Charts
# ==============================================================================
# Bar charts showing the percentage of subclones with 0, 1, or >1 significantly
# enriched gene sets (HALLMARK and REACTOME, up- and down-regulated separately).
#
# Input: summary_df — output of build_subclone_enrichment_summary()
#   (columns: Cancer_type, Study, Sample, comp, HALLMARK, REACTOME, ...)

plot_suppFig10_subclone_enrichment <- function(summary_df, db = "HALLMARK",
                                               direction_label = "up-regulated") {
  summary_df %>%
    mutate(category = case_when(
      .data[[db]] == 0 ~ "None",
      .data[[db]] == 1 ~ "One sig. pathway",
      .data[[db]] >= 2 ~ "More than one sig. pathway"
    )) %>%
    count(category) %>%
    mutate(
      Percentage = n / sum(n) * 100,
      category   = factor(category,
                          levels = c("None", "One sig. pathway",
                                     "More than one sig. pathway"))
    ) %>%
    ggplot(aes(x = category, y = Percentage)) +
    geom_col(fill = "gray30", alpha = 0.6) +
    geom_text(aes(label = paste0(round(Percentage, 1), "%")),
              nudge_y = 3, size = 5) +
    scale_x_discrete(labels = c(
      "None"                         = "None",
      "One sig. pathway"             = "One\nsig. pathway",
      "More than one sig. pathway"   = "More than one\nsig. pathway"
    )) +
    labs(y = paste0("% of Subclones with\nSignificantly Enriched\n",
                    db, " Gene Sets\n(", direction_label, ")"),
         x = "") +
    graph_theme
}

# ==============================================================================
# Recurrent Aneuploidy Correlation Heatmap
# ==============================================================================
# Heatmap showing whether (chromosome-arm, cancer-type) pairs have a positive,
# negative, or non-significant correlation with TCGA GSEA results.
#
# Input: df_count — data.frame with columns Arm, Type (cancer type),
#        label ("Concordant Direction" / "Discordant Direction" /
#               "Not significant"), Correlation, P_val

plot_correlation_heatmap <- function(df_count, db = "HALLMARK",
                                            cnv_type = "Loss") {
  library(stringr)
  df_count <- df_count %>%
    mutate(
      chr_num  = factor(str_extract(Arm, "^[0-9XY]+"),
                        levels = as.character(1:22)),
      arm_side = str_extract(Arm, "[pq]"),
      arm_order = if_else(arm_side == "p", 1, 2),
      label    = factor(label,
                        levels = c("Concordant Direction",
                                   "Discordant Direction",
                                   "Not significant"))
    ) %>%
    arrange(chr_num, arm_order, Type) %>%
    mutate(Arm = factor(Arm, levels = unique(Arm)))

  corr_colors <- c(
    "Concordant Direction" = "darkgreen",
    "Discordant Direction" = "purple4",
    "Not significant"      = "#cccccc"
  )

  ggplot(df_count, aes(x = Arm, y = Type, fill = label)) +
    geom_tile(color = "white") +
    scale_fill_manual(values = corr_colors) +
    labs(x = "Chromosome Arm",
         y = "Cancer Type",
         fill = paste0(pathways_titles_list[i], " Pathway\nEnrichment")) +
    graph_theme +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
          axis.line    = element_blank())
}

# ==============================================================================
# Single-Sample Gene Expression Violin Plot (Neutral vs. CNV)
# ==============================================================================
# Compares the expression of a specific gene between Neutral cells and cells 
# with a specific CNV (Loss/DEL or Gain/AMP) within a single patient sample.
#
# Input: gene_counts — data.frame with 'pred' (NEUTRAL, DEL, or AMP) and a column
#                      named after the target gene containing expression values.
#        gene        — character string of the gene name (e.g., "CDKN2A")
#        cnv_type    — character string, either "Loss" or "Gain"
#        title_text  — character string for the plot title

plot_single_sample_gene_exp <- function(gene_counts, gene, cnv_type, title_text) {
  
  cnv_label <- ifelse(cnv_type == 'Loss', 'DEL', 'AMP')
  cnv_display <- ifelse(cnv_type == 'Loss', 'Loss', 'Gain')
  
  # Ensure factors are set for plotting order
  gene_counts$pred <- factor(gene_counts$pred, levels = c("NEUTRAL", cnv_label))
  
  # Map dynamic labels for the x-axis
  x_labels <- c("NEUTRAL" = "Neutral")
  x_labels[cnv_label] <- cnv_display
  
  ggplot(gene_counts, aes(x = pred, y = get(gene))) +
    geom_violin(trim = FALSE, alpha = 0.6, fill = "gray") +
    geom_boxplot(width = 0.1, fill = 'white', outlier.shape = NA) +
    geom_jitter(alpha = 0.4, size = 1, width = 0.1, height = 0) +  
    stat_compare_means(
      method = "wilcox.test",
      comparisons = list(c("NEUTRAL", cnv_label)),
      label = "p.format",
      size = 5
    ) +
    scale_x_discrete(labels = x_labels) +
    labs(x = "", y = paste0(gene, " Expression")) +
    ggtitle(title_text) +
    graph_theme + 
    theme(axis.title = element_text(size = 15), 
          axis.text.y = element_text(size = 13), 
          plot.title = element_text(face = "plain", size = 17))
}

# ==============================================================================
# Average ssGSEA Enrichment Score (Paired Cross-Sample)
# ==============================================================================
# Compares the average ssGSEA enrichment score for a specific pathway between 
# Neutral and altered (Loss/Gain) cells, paired across multiple samples.
#
# Input: df_long      — paired data.frame containing:
#                       * 'condition': 'NEUTRAL' vs 'DEL' or 'AMP'.
#                       * 'value': average ssGSEA enrichment score 
#                                  calculated for that specific condition.
#        geneset_name — formatted character string for the y-axis label 
#                       (e.g., "SIGNALING_BY_TGF_BETA...")
#        cnv_type     — character string, either "Loss" or "Gain"

plot_avg_ssgsea_enrichment <- function(df_long, geneset_name, cnv_type) {
  
  cnv_label <- ifelse(cnv_type == 'Loss', 'DEL', 'AMP')
  cnv_display <- ifelse(cnv_type == 'Loss', 'Loss', 'Gain')
  
  df_long$condition <- factor(df_long$condition, levels = c('NEUTRAL', cnv_label))
  
  x_labels <- c("NEUTRAL" = "Neutral")
  x_labels[cnv_label] <- cnv_display
  
  ggplot(df_long, aes(x = condition, y = value)) +
    geom_violin(trim = FALSE, alpha = 0.6, fill = "gray") +
    geom_boxplot(width = 0.1, fill = 'white', outlier.shape = NA) +
    geom_jitter(alpha = 0.4, size = 1, width = 0.1, height = 0) +
    stat_compare_means(
      method = "wilcox.test",
      comparisons = list(c("NEUTRAL", cnv_label)),
      paired = TRUE,
      label = "p.format",
      size = 5
    ) +
    scale_x_discrete(labels = x_labels) +
    labs(x = "", y = paste0(geneset_name, "\nAverage ssGSEA Enrichment Score")) +
    graph_theme + 
    theme(axis.title = element_text(size = 15), 
          axis.text.y = element_text(size = 13))
}

# ==============================================================================
# Average Gene Expression (Paired Cross-Sample)
# ==============================================================================
# Compares the average expression of a specific gene between Neutral and altered 
# (Loss/Gain) cells, paired across multiple samples.
#
# Input: df_long  — paired data.frame with 'condition' and 'value'
#        gene     — character string of the gene name (e.g., "CDKN2A")
#        cnv_type — character string, either "Loss" or "Gain"

plot_avg_gene_expression <- function(df_long, gene, cnv_type) {
  
  cnv_label <- ifelse(cnv_type == 'Loss', 'DEL', 'AMP')
  cnv_display <- ifelse(cnv_type == 'Loss', 'Loss', 'Gain')
  
  df_long$condition <- factor(df_long$condition, levels = c('NEUTRAL', cnv_label))
  
  x_labels <- c("NEUTRAL" = "Neutral")
  x_labels[cnv_label] <- cnv_display
  
  ggplot(df_long, aes(x = condition, y = value)) +
    geom_violin(trim = FALSE, alpha = 0.6, fill = "gray") +
    geom_boxplot(width = 0.1, fill = 'white', outlier.shape = NA) +
    geom_jitter(alpha = 0.4, size = 1, width = 0.1, height = 0) +
    stat_compare_means(
      method = "wilcox.test",
      comparisons = list(c("NEUTRAL", cnv_label)),
      paired = TRUE,
      label = "p.format",
      size = 5
    ) +
    scale_x_discrete(labels = x_labels) +
    labs(x = "", y = paste0("Average ", gene, " Expression")) +
    graph_theme + 
    theme(axis.title = element_text(size = 15), 
          axis.text.y = element_text(size = 13))
}


# ==============================================================================
# Malignant vs. Non-Malignant Aneuploidy Baseline (Validation)
# ==============================================================================
# Violin/boxplot comparing baseline AS between malignant and non-malignant 
# cells using paired Wilcoxon rank-sum tests.
#
# Input: df_long — metadata mapped to long format with 'condition' 
#                  (Non_Malignant_Mean_AS, Malignant_Mean_AS) and 'value' (AS)
#        title_label — Label to differentiate parameter stringency

plot_malig_vs_nonmalig_AS <- function(df_long, title_label = "Lenient Parameters") {
  
  df_long$condition <- factor(df_long$condition, levels = c("Non_Malignant_Mean_AS", "Malignant_Mean_AS"))
  
  ggplot(df_long, aes(x = condition, y = value, fill = condition)) +
    geom_violin(trim = FALSE, alpha = 0.6) +
    geom_boxplot(width = 0.1, fill = 'white', outlier.shape = NA) +
    geom_jitter(alpha = 0.4, size = 1, width = 0.1, height = 0) + 
    stat_compare_means(
      method = "wilcox.test",
      comparisons = list(c('Non_Malignant_Mean_AS', 'Malignant_Mean_AS')),
      paired = TRUE,
      label = "p.format",
      size = 5
    ) +   
    labs(x = title_label, y = "Mean AS") +
    scale_fill_manual(
      values = c("Non_Malignant_Mean_AS" = "#cccccc", "Malignant_Mean_AS" = "#ff6666"),
      labels = c("Non-Malignant Cells", "Malignant Cells")
    ) +  
    scale_x_discrete(labels = c("Non_Malignant_Mean_AS" = "Non-Malignant\nMean AS", 
                                "Malignant_Mean_AS" = "Malignant\nMean AS")) +
    scale_y_continuous(limits = c(0, 18)) +  
    graph_theme + 
    theme(axis.title = element_text(size = 15), 
          axis.text.x = element_text(size = 13), 
          axis.text.y = element_text(size = 13), 
          legend.position = "none")
}
